/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as GuestForgotPasswordRouteImport } from './routes/_guest/forgot-password'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestResetPasswordRouteImport } from './routes/_guest/reset-password'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as AuthAppCalendarIdRouteRouteImport } from './routes/_auth/app/$calendarId/route'
import { Route as AuthAppNewRouteImport } from './routes/_auth/app/new'
import { Route as AuthAppSettingsRouteImport } from './routes/_auth/app/settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CalendarsCalendarIdChar123feedChar125DoticsRouteImport } from './routes/calendars/$calendarId/{$feed}[.]ics'
import { Route as AuthAppCalendarIdIndexRouteImport } from './routes/_auth/app/$calendarId/index'
import { Route as AuthAppCalendarIdScheduleRouteImport } from './routes/_auth/app/$calendarId/schedule'
import { Route as AuthAppCalendarIdSettingsRouteImport } from './routes/_auth/app/$calendarId/settings'
import { Route as AuthAppCalendarIdSubmissionsRouteImport } from './routes/_auth/app/$calendarId/submissions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestForgotPasswordRoute = GuestForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestResetPasswordRoute = GuestResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppCalendarIdRouteRoute = AuthAppCalendarIdRouteRouteImport.update({
  id: '/$calendarId',
  path: '/$calendarId',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppNewRoute = AuthAppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppSettingsRoute = AuthAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarsCalendarIdChar123feedChar125DoticsRoute =
  CalendarsCalendarIdChar123feedChar125DoticsRouteImport.update({
    id: '/calendars/$calendarId/{$feed}.ics',
    path: '/calendars/$calendarId/{$feed}.ics',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthAppCalendarIdIndexRoute = AuthAppCalendarIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppCalendarIdRouteRoute,
} as any)
const AuthAppCalendarIdScheduleRoute =
  AuthAppCalendarIdScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthAppCalendarIdRouteRoute,
  } as any)
const AuthAppCalendarIdSettingsRoute =
  AuthAppCalendarIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthAppCalendarIdRouteRoute,
  } as any)
const AuthAppCalendarIdSubmissionsRoute =
  AuthAppCalendarIdSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthAppCalendarIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/signup': typeof GuestSignupRoute
  '/app/$calendarId': typeof AuthAppCalendarIdRouteRouteWithChildren
  '/app/new': typeof AuthAppNewRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/calendars/$calendarId/{$feed}.ics': typeof CalendarsCalendarIdChar123feedChar125DoticsRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/$calendarId/schedule': typeof AuthAppCalendarIdScheduleRoute
  '/app/$calendarId/settings': typeof AuthAppCalendarIdSettingsRoute
  '/app/$calendarId/submissions': typeof AuthAppCalendarIdSubmissionsRoute
  '/app/$calendarId/': typeof AuthAppCalendarIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof GuestForgotPasswordRoute
  '/login': typeof GuestLoginRoute
  '/reset-password': typeof GuestResetPasswordRoute
  '/signup': typeof GuestSignupRoute
  '/app/new': typeof AuthAppNewRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/calendars/$calendarId/{$feed}.ics': typeof CalendarsCalendarIdChar123feedChar125DoticsRoute
  '/app': typeof AuthAppIndexRoute
  '/app/$calendarId/schedule': typeof AuthAppCalendarIdScheduleRoute
  '/app/$calendarId/settings': typeof AuthAppCalendarIdSettingsRoute
  '/app/$calendarId/submissions': typeof AuthAppCalendarIdSubmissionsRoute
  '/app/$calendarId': typeof AuthAppCalendarIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/forgot-password': typeof GuestForgotPasswordRoute
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/reset-password': typeof GuestResetPasswordRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_auth/app/$calendarId': typeof AuthAppCalendarIdRouteRouteWithChildren
  '/_auth/app/new': typeof AuthAppNewRoute
  '/_auth/app/settings': typeof AuthAppSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/calendars/$calendarId/{$feed}.ics': typeof CalendarsCalendarIdChar123feedChar125DoticsRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/$calendarId/schedule': typeof AuthAppCalendarIdScheduleRoute
  '/_auth/app/$calendarId/settings': typeof AuthAppCalendarIdSettingsRoute
  '/_auth/app/$calendarId/submissions': typeof AuthAppCalendarIdSubmissionsRoute
  '/_auth/app/$calendarId/': typeof AuthAppCalendarIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/$calendarId'
    | '/app/new'
    | '/app/settings'
    | '/api/auth/$'
    | '/calendars/$calendarId/{$feed}.ics'
    | '/app/'
    | '/app/$calendarId/schedule'
    | '/app/$calendarId/settings'
    | '/app/$calendarId/submissions'
    | '/app/$calendarId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/new'
    | '/app/settings'
    | '/api/auth/$'
    | '/calendars/$calendarId/{$feed}.ics'
    | '/app'
    | '/app/$calendarId/schedule'
    | '/app/$calendarId/settings'
    | '/app/$calendarId/submissions'
    | '/app/$calendarId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/_auth/app'
    | '/_guest/forgot-password'
    | '/_guest/login'
    | '/_guest/reset-password'
    | '/_guest/signup'
    | '/_auth/app/$calendarId'
    | '/_auth/app/new'
    | '/_auth/app/settings'
    | '/api/auth/$'
    | '/calendars/$calendarId/{$feed}.ics'
    | '/_auth/app/'
    | '/_auth/app/$calendarId/schedule'
    | '/_auth/app/$calendarId/settings'
    | '/_auth/app/$calendarId/submissions'
    | '/_auth/app/$calendarId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CalendarsCalendarIdChar123feedChar125DoticsRoute: typeof CalendarsCalendarIdChar123feedChar125DoticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/forgot-password': {
      id: '/_guest/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof GuestForgotPasswordRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/reset-password': {
      id: '/_guest/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof GuestResetPasswordRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/$calendarId': {
      id: '/_auth/app/$calendarId'
      path: '/$calendarId'
      fullPath: '/app/$calendarId'
      preLoaderRoute: typeof AuthAppCalendarIdRouteRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/new': {
      id: '/_auth/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AuthAppNewRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/settings': {
      id: '/_auth/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthAppSettingsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendars/$calendarId/{$feed}.ics': {
      id: '/calendars/$calendarId/{$feed}.ics'
      path: '/calendars/$calendarId/{$feed}.ics'
      fullPath: '/calendars/$calendarId/{$feed}.ics'
      preLoaderRoute: typeof CalendarsCalendarIdChar123feedChar125DoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/$calendarId/': {
      id: '/_auth/app/$calendarId/'
      path: '/'
      fullPath: '/app/$calendarId/'
      preLoaderRoute: typeof AuthAppCalendarIdIndexRouteImport
      parentRoute: typeof AuthAppCalendarIdRouteRoute
    }
    '/_auth/app/$calendarId/schedule': {
      id: '/_auth/app/$calendarId/schedule'
      path: '/schedule'
      fullPath: '/app/$calendarId/schedule'
      preLoaderRoute: typeof AuthAppCalendarIdScheduleRouteImport
      parentRoute: typeof AuthAppCalendarIdRouteRoute
    }
    '/_auth/app/$calendarId/settings': {
      id: '/_auth/app/$calendarId/settings'
      path: '/settings'
      fullPath: '/app/$calendarId/settings'
      preLoaderRoute: typeof AuthAppCalendarIdSettingsRouteImport
      parentRoute: typeof AuthAppCalendarIdRouteRoute
    }
    '/_auth/app/$calendarId/submissions': {
      id: '/_auth/app/$calendarId/submissions'
      path: '/submissions'
      fullPath: '/app/$calendarId/submissions'
      preLoaderRoute: typeof AuthAppCalendarIdSubmissionsRouteImport
      parentRoute: typeof AuthAppCalendarIdRouteRoute
    }
  }
}

interface AuthAppCalendarIdRouteRouteChildren {
  AuthAppCalendarIdScheduleRoute: typeof AuthAppCalendarIdScheduleRoute
  AuthAppCalendarIdSettingsRoute: typeof AuthAppCalendarIdSettingsRoute
  AuthAppCalendarIdSubmissionsRoute: typeof AuthAppCalendarIdSubmissionsRoute
  AuthAppCalendarIdIndexRoute: typeof AuthAppCalendarIdIndexRoute
}

const AuthAppCalendarIdRouteRouteChildren: AuthAppCalendarIdRouteRouteChildren =
  {
    AuthAppCalendarIdScheduleRoute: AuthAppCalendarIdScheduleRoute,
    AuthAppCalendarIdSettingsRoute: AuthAppCalendarIdSettingsRoute,
    AuthAppCalendarIdSubmissionsRoute: AuthAppCalendarIdSubmissionsRoute,
    AuthAppCalendarIdIndexRoute: AuthAppCalendarIdIndexRoute,
  }

const AuthAppCalendarIdRouteRouteWithChildren =
  AuthAppCalendarIdRouteRoute._addFileChildren(
    AuthAppCalendarIdRouteRouteChildren,
  )

interface AuthAppRouteRouteChildren {
  AuthAppCalendarIdRouteRoute: typeof AuthAppCalendarIdRouteRouteWithChildren
  AuthAppNewRoute: typeof AuthAppNewRoute
  AuthAppSettingsRoute: typeof AuthAppSettingsRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppCalendarIdRouteRoute: AuthAppCalendarIdRouteRouteWithChildren,
  AuthAppNewRoute: AuthAppNewRoute,
  AuthAppSettingsRoute: AuthAppSettingsRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestForgotPasswordRoute: typeof GuestForgotPasswordRoute
  GuestLoginRoute: typeof GuestLoginRoute
  GuestResetPasswordRoute: typeof GuestResetPasswordRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestForgotPasswordRoute: GuestForgotPasswordRoute,
  GuestLoginRoute: GuestLoginRoute,
  GuestResetPasswordRoute: GuestResetPasswordRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CalendarsCalendarIdChar123feedChar125DoticsRoute:
    CalendarsCalendarIdChar123feedChar125DoticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
